version: '3'

services:
  inference:
    container_name: net1-worker1-inference
    build:
      context: .
    command: python -u /app/app.py
    ports:
      - "8011:8011"
    networks:
      net1-worker1:
        aliases:
          - inference
        ipv4_address: 172.31.0.2
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:8011/inference/ETH"]
      test: ["CMD-SHELL", "curl -f http://localhost:8011/inference/ETH || exit 1 && curl -f http://localhost:8011/inference/BTC || exit 1 && curl -f http://localhost:8011/inference/SOL || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 300s
    volumes:
      - ./inference-data:/app/data
  
  updater:
    container_name: net1-updater1
    build: .
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8011
    command: >
      sh -c "
      while true; do
        python -u /app/update_app.py;
        sleep 600;  # 300 seconds (5 minutes)
      done
      "
    depends_on:
      inference:
        condition: service_healthy
    networks:
      net1-worker1:
        aliases:
          - updater
        ipv4_address: 172.31.0.3
    
  worker_topic_7:
    container_name: net1-worker1-topic-7
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8011
      - HOME=/data
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker --peer-db=/data/peerdb --function-db=/data/function-db \
          --runtime-path=/app/runtime --runtime-cli=bls-runtime --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin --log-level=debug --port=9101 \
          --boot-nodes=/ip4/45.149.205.38/tcp/9103/p2p/12D3KooWRx6t75bDV9MAEfPobEZj8YoUEYs1GgSSgG2n8FF7aoA5 \
          --topic=allora-topic-7-worker \
          --allora-chain-key-name=net1_worker \
          --allora-chain-restore-mnemonic='song job proud mask ramp pole era siege pledge veteran expand music' \
          --allora-chain-topic-id=7 \
          --allora-node-rpc-address=https://allora-rpc.testnet-1.testnet.allora.network \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-7-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9101:9101"
    networks:
      net1-worker1:
        aliases:
          - worker_topic_1
        ipv4_address: 172.31.0.21

networks:
  net1-worker1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24

volumes:
  inference-data:
  worker-topic-7-data: