version: '3'

services:
  inference:
    container_name: net1-worker2-inference
    build:
      context: .
    command: python -u /app/app.py
    ports:
      - "8010:8010"
    networks:
      net1-worker2:
        aliases:
          - inference
        ipv4_address: 172.32.0.2
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:8010/inference/ETH"]
      test: ["CMD-SHELL", "curl -f http://localhost:8010/inference/ETH || exit 1 && curl -f http://localhost:8010/inference/BTC || exit 1 && curl -f http://localhost:8010/inference/SOL || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 300s
    volumes:
      - ./inference-data:/app/data
  
  updater:
    container_name: net1-updater2
    build: .
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8010
    command: >
      sh -c "
      while true; do
        python -u /app/update_app.py;
        sleep 12h;
      done
      "
    depends_on:
      inference:
        condition: service_healthy
    networks:
      net1-worker2:
        aliases:
          - updater
        ipv4_address: 172.32.0.3
    
  worker_topic_2:
    container_name: net1-worker2-topic-2
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8010
      - HOME=/data
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker --peer-db=/data/peerdb --function-db=/data/function-db \
          --runtime-path=/app/runtime --runtime-cli=bls-runtime --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin --log-level=debug --port=9102 \
          --dialback-address=ip_server --dialback-port=9102 \
          --boot-nodes=/dns/head-0-p2p.testnet-1.testnet.allora.network/tcp/32130/p2p/12D3KooWLBhsSucVVcyVCaM9pvK8E7tWBM9L19s7XQHqqejyqgEC,/dns/head-1-p2p.testnet-1.testnet.allora.network/tcp/32131/p2p/12D3KooWEUNWg7YHeeCtH88ju63RBfY5hbdv9hpv84ffEZpbJszt,/dns/head-2-p2p.testnet-1.testnet.allora.network/tcp/32132/p2p/12D3KooWATfUSo95wtZseHbogpckuFeSvpL4yks6XtvrjVHcCCXk \
          --topic=allora-topic-2-worker \
          --allora-chain-key-name=net1_worker \
          --allora-chain-restore-mnemonic='just clap slim ...' \
          --allora-chain-topic-id=2 \
          --allora-node-rpc-address=https://allora-rpc.testnet-1.testnet.allora.network \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-2-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9102:9102"
    networks:
      net1-worker2:
        aliases:
          - worker_topic_2
        ipv4_address: 172.32.0.21

  worker_topic_4:
    container_name: net1-worker2-topic-4
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8010
      - HOME=/data
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker --peer-db=/data/peerdb --function-db=/data/function-db \
          --runtime-path=/app/runtime --runtime-cli=bls-runtime --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin --log-level=debug --port=9104 \
          --dialback-address=ip_server --dialback-port=9104 \
          --boot-nodes=/dns/head-0-p2p.testnet-1.testnet.allora.network/tcp/32130/p2p/12D3KooWLBhsSucVVcyVCaM9pvK8E7tWBM9L19s7XQHqqejyqgEC,/dns/head-1-p2p.testnet-1.testnet.allora.network/tcp/32131/p2p/12D3KooWEUNWg7YHeeCtH88ju63RBfY5hbdv9hpv84ffEZpbJszt,/dns/head-2-p2p.testnet-1.testnet.allora.network/tcp/32132/p2p/12D3KooWATfUSo95wtZseHbogpckuFeSvpL4yks6XtvrjVHcCCXk \
          --topic=allora-topic-4-worker \
          --allora-chain-key-name=net1_worker \
          --allora-chain-restore-mnemonic='just clap slim ...' \
          --allora-chain-topic-id=4 \
          --allora-node-rpc-address=https://allora-rpc.testnet-1.testnet.allora.network \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-4-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9104:9104"
    networks:
      net1-worker2:
        aliases:
          - worker_topic_4
        ipv4_address: 172.32.0.23

  worker_topic_6:
    container_name: net1-worker2-topic-6
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8010
      - HOME=/data
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker --peer-db=/data/peerdb --function-db=/data/function-db \
          --runtime-path=/app/runtime --runtime-cli=bls-runtime --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin --log-level=debug --port=9106 \
          --dialback-address=ip_server --dialback-port=9106 \
          --boot-nodes=/dns/head-0-p2p.testnet-1.testnet.allora.network/tcp/32130/p2p/12D3KooWLBhsSucVVcyVCaM9pvK8E7tWBM9L19s7XQHqqejyqgEC,/dns/head-1-p2p.testnet-1.testnet.allora.network/tcp/32131/p2p/12D3KooWEUNWg7YHeeCtH88ju63RBfY5hbdv9hpv84ffEZpbJszt,/dns/head-2-p2p.testnet-1.testnet.allora.network/tcp/32132/p2p/12D3KooWATfUSo95wtZseHbogpckuFeSvpL4yks6XtvrjVHcCCXk \
          --topic=allora-topic-6-worker \
          --allora-chain-key-name=net1_worker \
          --allora-chain-restore-mnemonic='just clap slim ...' \
          --allora-chain-topic-id=6 \
          --allora-node-rpc-address=https://allora-rpc.testnet-1.testnet.allora.network \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-6-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9106:9106"
    networks:
      net1-worker2:
        aliases:
          - worker_topic_6
        ipv4_address: 172.32.0.25
  
networks:
  net1-worker2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/24

volumes:
  inference-data:
  worker-topic-2-data:
  worker-topic-4-data:
  worker-topic-6-data: